import type { Metadata } from "next";
import { Playfair_Display, Lato } from "next/font/google";
import "./globals.css";
import { Context } from "./Context";
import StoreProvider from "./StoreProvider";
import MultiLangProvider from "@/lib/Providers/MultiLangProvider";
import TranslationButton from "@/components/TranslationButton";

const playfairDisplay = Playfair_Display({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-playfair-display",
});

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "BEAUTY SERVVICE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${playfairDisplay.variable} ${lato.variable}`}>
      <body className="font-lato max-w-[1920px] mx-auto">
        {/* <MultiLangProvider> */}
          {/* <TranslationButton /> */}
          <StoreProvider>
            <Context>{children}</Context>
          </StoreProvider>
        {/* </MultiLangProvider> */}
      </body>
    </html>
  );
}
